<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\RonSijm.Blazyload.Components\RonSijm.Blazyload.Components.csproj" />
    <ProjectReference Include="..\RonSijm.Demo.Blazyload.Components.Pizza.Contracts\RonSijm.Demo.Blazyload.Components.Pizza.Contracts.csproj" />
    <ProjectReference Include="..\RonSijm.Demo.Blazyload.Components.Pizza.Services\RonSijm.Demo.Blazyload.Components.Pizza.Services.csproj" />
  </ItemGroup>
</Project>
