<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" PrivateAssets="all" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="bunit" Version="2.5.3" />
    <PackageReference Include="AngleSharp" Version="1.8.3" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.14.28" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" />
    <Using Include="Xunit" />
    <ProjectReference Include="..\..\src\RonSijm.Blazyload.Components\RonSijm.Blazyload.Components.csproj" />
    <ProjectReference Include="..\..\src\RonSijm.Blazyload.Components.Build\RonSijm.Blazyload.Components.Build.csproj" />
    <ProjectReference Include="..\..\src\RonSijm.Blazyload.Components.SourceGenerator\RonSijm.Blazyload.Components.SourceGenerator.csproj" />
    <ProjectReference Include="..\..\src\RonSijm.Blazyload.Components.SourceGenerator.Build\RonSijm.Blazyload.Components.SourceGenerator.Build.csproj" />
    <BlazyComponentContractReference Include="..\..\Examples\Extensive\RonSijm.Demo.WonderWharf\RonSijm.Demo.WonderWharf.csproj" />
    <ProjectReference Include="..\..\Examples\Extensive\RonSijm.Demo.WonderWharf\RonSijm.Demo.WonderWharf.csproj" />
    <ProjectReference Include="..\..\Examples\Extensive\RonSijm.Demo.BobsBurgers\RonSijm.Demo.BobsBurgers.csproj" />
    <ProjectReference Include="..\..\Examples\Simple\RonSijm.Demo.Blazyload.Components.Burger\RonSijm.Demo.Blazyload.Components.Burger.csproj" />
    <ProjectReference Include="..\..\Examples\Simple\RonSijm.Demo.Blazyload.Components.Pizza\RonSijm.Demo.Blazyload.Components.Pizza.csproj" />
  </ItemGroup>
</Project>
