using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace RonSijm.Blazyload.Components.SourceGenerator;

[Generator]
public sealed class ComponentContractGenerator() : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor InvalidDeclaration = new("BLZCON101", "Invalid component contract", "{0}", "Blazyload.Contracts", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor DuplicateIdentifier = new("BLZCON102", "Duplicate component contract", "{0}", "Blazyload.Contracts", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor InvalidName = new("BLZCON103", "Invalid generated contract name", "{0}", "Blazyload.Contracts", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(output => output.AddSource("BlazyContractAttribute.g.cs", SourceText.From("""
            // <auto-generated />
            namespace RonSijm.Blazyload.Components
            {
                [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct | global::System.AttributeTargets.Enum | global::System.AttributeTargets.Interface | global::System.AttributeTargets.Delegate, AllowMultiple = false, Inherited = false)]
                internal sealed class BlazyContractAttribute : global::System.Attribute
                {
                }
            }
            """, Encoding.UTF8)));

        var files = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase) || file.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase))
            .Select((file, cancellationToken) => new ContractInput(file.Path, file.GetText(cancellationToken)?.ToString()));
        context.RegisterSourceOutput(files.Collect().Combine(context.ParseOptionsProvider).Combine(context.AnalyzerConfigOptionsProvider), (output, input) => Generate(output, input.Left.Left, (CSharpParseOptions)input.Left.Right, input.Right.GlobalOptions));
    }

    private static void Generate(SourceProductionContext output, ImmutableArray<ContractInput> files, CSharpParseOptions parseOptions, AnalyzerConfigOptions options)
    {
        if (!options.TryGetValue("build_property.BlazyContractsCompilation", out var enabled) || !string.Equals(enabled, "true", StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        options.TryGetValue("build_property.BlazyContractsNamespace", out var contractNamespace);
        options.TryGetValue("build_property.BlazyContractsClassName", out var className);
        if (string.IsNullOrWhiteSpace(contractNamespace) || contractNamespace!.Split('.').Any(part => !SyntaxFacts.IsValidIdentifier(part)) || string.IsNullOrWhiteSpace(className) || !SyntaxFacts.IsValidIdentifier(className))
        {
            output.ReportDiagnostic(Diagnostic.Create(InvalidName, Location.None, "The contracts namespace and class name must be valid C# identifiers."));
            return;
        }

        var entries = new SortedDictionary<string, string>(StringComparer.Ordinal);
        var names = new HashSet<string>(StringComparer.Ordinal);
        foreach (var file in files.OrderBy(file => file.Path, StringComparer.Ordinal))
        {
            if (file.Text is null)
            {
                output.ReportDiagnostic(Diagnostic.Create(InvalidDeclaration, Location.None, $"Cannot read contract input '{file.Path}'."));
                continue;
            }

            foreach (var attribute in GetAttributes(file, parseOptions))
            {
                if (!ContractAttributeNames.Matches(attribute, "BlazyComponent"))
                {
                    continue;
                }

                var argument = attribute.ArgumentList?.Arguments.FirstOrDefault()?.Expression;
                if (argument is not LiteralExpressionSyntax literal || !literal.IsKind(SyntaxKind.StringLiteralExpression) || string.IsNullOrWhiteSpace(literal.Token.ValueText))
                {
                    output.ReportDiagnostic(Diagnostic.Create(InvalidDeclaration, Location.None, $"{file.Path}: exported component names must be nonempty string literals."));
                    continue;
                }

                var name = literal.Token.ValueText;
                var member = MakeIdentifier(name.Split('.').Last());
                if (member.Length == 0 || !SyntaxFacts.IsValidIdentifier(member) || member == className)
                {
                    output.ReportDiagnostic(Diagnostic.Create(InvalidDeclaration, Location.None, $"{file.Path}: component '{name}' cannot produce a C# identifier."));
                    continue;
                }

                if (!names.Add(name) || entries.ContainsKey(member))
                {
                    output.ReportDiagnostic(Diagnostic.Create(DuplicateIdentifier, Location.None, $"Component '{name}' produces a duplicate name or member '{member}'. Use distinct logical-name suffixes."));
                    continue;
                }

                entries.Add(member, name);
            }
        }

        var source = new StringBuilder("// <auto-generated />\n");
        source.Append("namespace ").Append(contractNamespace).Append("\n{\n    public static class ").Append(className).Append("\n    {\n");
        foreach (var entry in entries)
        {
            source.Append("        public const string ").Append(entry.Key).Append(" = ").Append(SymbolDisplay.FormatLiteral(entry.Value, quote: true)).Append(";\n");
        }

        source.Append("    }\n}\n");
        output.AddSource($"{className}.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static IEnumerable<AttributeSyntax> GetAttributes(ContractInput input, CSharpParseOptions parseOptions)
    {
        if (input.Path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
        {
            var root = CSharpSyntaxTree.ParseText(input.Text!, parseOptions).GetRoot();
            return root.DescendantNodes().OfType<TypeDeclarationSyntax>().SelectMany(type => type.AttributeLists.SelectMany(list => list.Attributes));
        }

        var attributes = new List<AttributeSyntax>();
        var offset = 0;
        while (offset < input.Text!.Length)
        {
            var start = input.Text.IndexOf('@', offset);
            if (start < 0)
            {
                break;
            }

            offset = start + 1;
            var remaining = input.Text.Substring(start);
            if (remaining.StartsWith("@*", StringComparison.Ordinal))
            {
                var end = input.Text.IndexOf("*@", start + 2, StringComparison.Ordinal);
                if (end < 0)
                {
                    break;
                }

                offset = end + 2;
                continue;
            }

            if (remaining.StartsWith("@code", StringComparison.Ordinal) || remaining.StartsWith("@functions", StringComparison.Ordinal))
            {
                var brace = input.Text.IndexOf('{', start);
                if (brace >= 0)
                {
                    offset = brace + ReadBalancedEnd(input.Text.Substring(brace), SyntaxKind.OpenBraceToken, SyntaxKind.CloseBraceToken);
                }

                continue;
            }

            if (!remaining.StartsWith("@attribute", StringComparison.Ordinal))
            {
                continue;
            }

            offset = start + "@attribute".Length;
            var lineStart = input.Text.LastIndexOf('\n', start);
            if (input.Text.Substring(lineStart + 1, start - lineStart - 1).Trim().Length != 0)
            {
                continue;
            }

            var remainder = input.Text.Substring(offset).TrimStart();
            if (!remainder.StartsWith("[", StringComparison.Ordinal))
            {
                continue;
            }

            var usings = string.Join("\n", input.Text.Split('\n').Select(line => line.Trim()).Where(line => line.StartsWith("@using ", StringComparison.Ordinal)).Select(line => line.Substring(1).TrimEnd(';', '\r') + ";"));
            var declaration = CSharpSyntaxTree.ParseText(usings + "\n" + remainder.Substring(0, ReadBalancedEnd(remainder, SyntaxKind.OpenBracketToken, SyntaxKind.CloseBracketToken)) + "\nclass __ContractProbe {}", parseOptions).GetRoot();
            attributes.AddRange(declaration.DescendantNodes().OfType<AttributeSyntax>());
        }

        return attributes;
    }

    private static int ReadBalancedEnd(string text, SyntaxKind opening, SyntaxKind closing)
    {
        var depth = 0;
        foreach (var token in SyntaxFactory.ParseTokens(text))
        {
            if (token.IsKind(opening))
            {
                depth++;
            }
            else if (token.IsKind(closing))
            {
                depth--;
                if (depth == 0)
                {
                    return token.Span.End;
                }
            }
        }

        return text.Length;
    }

    private static string MakeIdentifier(string value)
    {
        var result = new StringBuilder();
        var capitalize = true;
        foreach (var character in value)
        {
            if (!char.IsLetterOrDigit(character) && character != '_')
            {
                capitalize = true;
                continue;
            }

            if (result.Length == 0 && char.IsDigit(character))
            {
                result.Append('_');
            }

            result.Append(capitalize ? char.ToUpperInvariant(character) : character);
            capitalize = false;
        }

        return result.ToString();
    }

    private sealed class ContractInput(string path, string? text)
    {
        public string Path { get; } = path;
        public string? Text { get; } = text;
    }
}
